import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import supabaseClient from '../utils/supabase';

export async function getStaticProps() {
  const { data: posts, error } = await supabaseClient.from('posts').select('*');

  if (error) {
    throw new Error('Something went wrong while fetching posts', error);
  }

  return {
    props: {
      posts
    }
  };
}

export default function Home({ posts }) {
  console.log(supabaseClient.auth.user());
  return (
    <div className={styles.container}>
      <Head>
        <title>Supablog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Welcome to Supablog</h1>
        <pre>{JSON.stringify(posts, null, 2)}</pre>
      </main>
    </div>
  );
}
